export const LOAD_PERSON = "LOAD_PERSON";
export const LOADING_ERROR = "LOADING_ERROR";
export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
export const GET_QUOTE = "GET_QUOTE";
export const STORE_IN_LOCALSTORAGE = "STORE_IN_LOCALSTORAGE";