export const GET_PERSON = "GET_PERSON";
export const GET_PERSON_LIST = "GET_PERSON_LIST";
export const LOADING_ERROR = "LOADING_ERROR";
export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
export const GET_QUOTE = "GET_QUOTE";