export const SET_CHARACTERS = "SET_CHARACTERS";
export const CHANGE_CHARACTERS_LOADER_VALUE = "CHANGE_CHARACTERS_LOADER_VALUE";
export const ERROR_GETTING_CHARACTERS = "ERROR_GETTING_CHARACTERS";
export const GET_QUOTE = "GET_QUOTE";
export const QUOTE_LOADER_VALUE = "QUOTE_LOADER_VALUE";
export const ERROR_GETTING_QUOTE = "ERROR_GETTING_QUOTE";