export const HOME_PAGE_LOAD = "HOME_PAGE_LOAD";
export const CATALOG_FORMAT = "CATALOG_FORMAT";
export const CHANGE_ELEMENT_COUNT = "CHANGE_ELEMENT_COUNT";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"